version: "3"
services:

  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./nginx/templates:/etc/nginx/templates
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - user-service
      - product-service
      - order-service
    networks:
      - sangwon_network

  user-service:
    build:
      context: ./user
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ./user/.env
    depends_on:
      - rabbitmq
      - user-db
    networks:
      - sangwon_network

  product-service:
    build:
      context: ./product
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    env_file:
      - ./product/.env
    depends_on:
      - product-db
    networks:
      - sangwon_network

  order-service:
    build:
      context: ./order
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    env_file:
      - ./order/.env
    depends_on:
      - order-db
    networks:
      - sangwon_network

  user-db:
    container_name: user_db
    image: postgres:latest
    ports:
      - "5432:5432"  # Mapping host port 5432 to container port 5432
    volumes:
      - user-db:/var/lib/postgresql/data
    env_file:
      - ./user/.env
    networks:
      - sangwon_network

  product-db:
    container_name: product_db
    image: postgres:latest
    ports:
      - "5433:5432"  # Mapping host port 5433 to container port 5432
    volumes:
      - product-db:/var/lib/postgresql/data
    env_file:
      - ./product/.env
    networks:
      - sangwon_network

  order-db:
    container_name: order_db
    image: postgres:latest
    ports:
      - "5434:5432"  # Mapping host port 5434 to container port 5432
    volumes:
      - order-db:/var/lib/postgresql/data
    env_file:
      - ./order/.env
    networks:
      - sangwon_network

  rabbitmq:
    image: rabbitmq:3.9-management
    container_name: rabbitmq
    restart: always
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - sangwon_network

  redis:
    container_name: sangwon_redis
    image: "redis:alpine"
    env_file:
      - ./user/.env
    ports:
      - "6379:6379"
    networks:
      - sangwon_network

networks:
  sangwon_network:
    driver: bridge

volumes:
  user-db:
  product-db:
  order-db:
  rabbitmq_data:


#version: "3"
#services:
#
#  nginx:
#    image: nginx:stable-alpine
#    volumes:
#      - ./nginx/templates:/etc/nginx/templates
#      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
#    ports:
#      - "80:80"
#    depends_on:
#      - user-service
#      - product-service
#      - order-service
#    networks:
#      - sangwon_network
#
#
#  user-service:
#    build:
#      context: ./user
#      dockerfile: Dockerfile
#    ports:
#      - "3000:3000"
#    env_file:
#      - ./user/.env
#    depends_on:
#      - rabbitmq
#    networks:
#      - sangwon_network
#
#  product-service:
#    build:
#      context: ./product
#      dockerfile: Dockerfile
#    ports:
#      - "3001:3001"
#    env_file:
#      - ./product/.env
#    networks:
#      - sangwon_network
#
#  order-service:
#    build:
#      context: ./order
#      dockerfile: Dockerfile
#    ports:
#      - '3002:3002'
#    env_file:
#      - ./order/.env
#    networks:
#      - sangwon_network
#
#  user-db:
#    container_name: user_db
#    image: postgres:latest
#    ports:
#      - "5432:5432"  # Mapping host port 5432 to container port 5432
#    volumes:
#      - user-db:/var/lib/postgresql/data
#    env_file:
#      - ./user/.env
#    networks:
#      - sangwon_network
#
#  product-db:
#    container_name: product_db
#    image: postgres:latest
#    ports:
#      - "5433:5432"  # Mapping host port 5433 to container port 5432
#    volumes:
#      - product-db:/var/lib/postgresql/data
#    env_file:
#      - ./product/.env
#    networks:
#      - sangwon_network
#
#  order-db:
#    container_name: order_db
#    image: postgres:latest
#    ports:
#      - "5434:5432"  # Mapping host port 5434 to container port 5432
#    volumes:
#      - order-db:/var/lib/postgresql/data
#    env_file:
#      - ./order/.env
#    networks:
#      - sangwon_network
#
##  postgres:
##    image: postgres:latest
##    ports:
##      - '5432:5432'
##    environment:
##      - POSTGRES_USER=sangwon_user
##      - POSTGRES_PASSWORD=sangwon_password
##      - POSTGRES_DB=sangwondb
##    volumes:
##      - pg_data:/var/lib/postgresql/data
#
#  rabbitmq:
#    image: rabbitmq:3.9-management
#    container_name: rabbitmq
#    restart: always
#    hostname: rabbitmq
#    ports:
#      - "5672:5672"
#      - "15672:15672"
#    volumes:
#      - rabbitmq_data:/var/lib/rabbitmq
#    networks:
#      - sangwon_network
#    #    environment:
#  #      RABBITMQ_DEFAULT_USER: admin
#  #      RABBITMQ_DEFAULT_PASS: password
#  #    cpus: 0.1
#  #    mem_limit: 256M
#
#
#
#
#networks:
#  sangwon_network:
#    driver: bridge
#
#volumes:
#  pg_data:
#    driver: local
#  rabbitmq_data:

