version: "3"
services:

  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./nginx/templates:/etc/nginx/templates
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - user-service
      - product-service
      - order-service
    networks:
      - sangwon_network

  rabbitmq:
    image: rabbitmq:3.9-management
    container_name: rabbitmq
    restart: always
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - sangwon_network
  #    environment:
#      RABBITMQ_DEFAULT_USER: admin
#      RABBITMQ_DEFAULT_PASS: password
#    cpus: 0.1
#    mem_limit: 256M




  user-service:
    build:
      context: ./user
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - rabbitmq
    networks:
      - sangwon_network

  product-service:
    build:
      context: ./product
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    networks:
      - sangwon_network

  order-service:
    build:
      context: ./order
      dockerfile: Dockerfile
    ports:
      - '3002:3002'
    networks:
      - sangwon_network

  postgres:
    image: postgres:latest
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=sangwon_user
      - POSTGRES_PASSWORD=sangwon_password
      - POSTGRES_DB=sangwondb
    volumes:
      - pg_data:/var/lib/postgresql/data


networks:
  sangwon_network:
    driver: bridge

volumes:
  pg_data:
    driver: local
  rabbitmq_data:
